import React, { useState, useEffect } from 'react';
import Pagination, { usePagination } from '../common/Pagination';
import { getPayments, savePayment, deletePayment, getInvoices, getAccounts, getCurrentUser, getCompanies, getCustomerLedger, applyContactPayment, getVendorLedger, applyVendorPayment, getPurchaseCosts, hasPermission, subscribeToEvents, getCustomerWalletBalance, getCustomerWalletTransactions, useFromCustomerWallet, formatCurrencyWithRate } from '../../data/store';

export default function Payments() {
  const [payments, setPayments] = useState([]);
  const [invoices, setInvoices] = useState([]);
  const [accounts, setAccounts] = useState([]);
  const [companies, setCompanies] = useState([]);
  const [purchaseCosts, setPurchaseCosts] = useState([]);
  const [showModal, setShowModal] = useState(false);
  const [showCustomerModal, setShowCustomerModal] = useState(false);
  const [showVendorModal, setShowVendorModal] = useState(false);
  const [editingPayment, setEditingPayment] = useState(null);
  const [filterType, setFilterType] = useState('all');
  const [searchTerm, setSearchTerm] = useState('');

  const loadData = () => {
    getPayments().then(setPayments).catch(() => {});
    getAccounts().then(setAccounts).catch(() => {});
    getInvoices().then(setInvoices).catch(() => {});
    getCompanies().then(setCompanies).catch(() => {});
    getPurchaseCosts().then(setPurchaseCosts).catch(() => {});
  };

  // Initial load + keep fresh whenever anything changes
  useEffect(() => { loadData(); }, []);

  useEffect(() => {
    const unsubscribe = subscribeToEvents((event) => {
      const refreshEvents = [
        'payment_saved', 'payment_deleted',
        'account_balance_updated',
        'invoice_updated', 'purchaseCost_updated',
      ];
      if (refreshEvents.includes(event.type)) loadData();
    });
    return unsubscribe;
  }, []);

  const handleSave = (payment) => {
    savePayment(payment).then(() => loadData()).catch(() => {});
    setShowModal(false);
    setEditingPayment(null);
  };

  const handleDelete = (id) => {
    if (confirm('Are you sure you want to delete this payment?')) {
      deletePayment(id).then(() => loadData()).catch(() => {});
    }
  };

  const handleEdit = (payment) => {
    setEditingPayment(payment);
    setShowModal(true);
  };

  const printPaymentVoucher = (payment) => {
    const fmtCur = (n) => Number(n || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Payment Voucher</title>
      <style>
        body{font-family:Arial,sans-serif;padding:40px;color:#1e293b;max-width:600px;margin:0 auto}
        h1{color:#3b82f6;margin:0 0 4px;font-size:22px}
        .ref{color:#64748b;font-size:13px;margin-bottom:24px}
        table{width:100%;border-collapse:collapse;margin-top:16px}
        td{padding:10px 0;border-bottom:1px solid #f1f5f9;font-size:14px}
        td:first-child{color:#64748b;width:40%}
        .amount{font-size:28px;font-weight:bold;color:#1e293b;margin:24px 0}
        footer{margin-top:32px;font-size:11px;color:#94a3b8;text-align:center;border-top:1px solid #e2e8f0;padding-top:12px}
        @media print{body{padding:20px}}
      </style>
    </head><body>
      <h1>Payment Voucher</h1>
      <div class="ref">Ref: ${payment.reference || payment.id}</div>
      <div class="amount">${(payment.type === 'inbound' ? '+' : '-')} $${fmtCur(payment.amount)}</div>
      <table>
        <tr><td>Date</td><td>${payment.date || ''}</td></tr>
        <tr><td>Type</td><td>${payment.type === 'inbound' ? 'Inbound (Received)' : 'Outbound (Paid)'}</td></tr>
        <tr><td>Method</td><td>${payment.method || ''}</td></tr>
        ${payment.reference ? `<tr><td>Reference / Cheque #</td><td>${payment.reference}</td></tr>` : ''}
        ${payment.description ? `<tr><td>Description</td><td>${payment.description}</td></tr>` : ''}
        ${payment.companyName ? `<tr><td>Party</td><td>${payment.companyName}</td></tr>` : ''}
        ${payment.notes ? `<tr><td>Notes</td><td>${payment.notes}</td></tr>` : ''}
      </table>
      <footer>Generated by ERP System &bull; ${new Date().toLocaleString()}</footer>
      <script>window.onload=()=>{window.print();}</script>
    </body></html>`;
    const w = window.open('', '_blank', 'width=700,height=600');
    if (w) { w.document.write(html); w.document.close(); }
  };

  const filteredPayments = (() => {
    let list = filterType === 'all' ? payments : payments.filter(p => p.type === filterType);
    if (searchTerm.trim()) {
      const q = searchTerm.toLowerCase();
      list = list.filter(p =>
        p.reference?.toLowerCase().includes(q) ||
        p.invoiceId?.toLowerCase().includes(q) ||
        p.companyName?.toLowerCase().includes(q) ||
        p.method?.toLowerCase().includes(q) ||
        p.type?.toLowerCase().includes(q) ||
        p.notes?.toLowerCase().includes(q) ||
        String(p.amount || '').includes(q)
      );
    }
    return list;
  })();

  const paymentPagination = usePagination(filteredPayments, 50);

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  const formatDate = (date) => {
    return new Date(date).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const getMethodColor = (method) => {
    const colors = {
      cash: 'bg-green-100 text-green-700',
      check: 'bg-blue-100 text-blue-700',
      bank_transfer: 'bg-purple-100 text-purple-700',
      credit_card: 'bg-orange-100 text-orange-700'
    };
    return colors[method] || 'bg-gray-100 text-gray-700';
  };

  const getMethodLabel = (method) => {
    const labels = {
      cash: 'Cash',
      check: 'Check',
      bank_transfer: 'Bank Transfer',
      credit_card: 'Credit Card'
    };
    return labels[method] || method;
  };

  // Calculate totals
  const inboundPayments = payments.filter(p => p.type === 'inbound' || p.invoiceId);
  const outboundPayments = payments.filter(p => p.type === 'outbound' && !p.invoiceId);
  const totalInbound = inboundPayments.reduce((sum, p) => sum + p.amount, 0);
  const totalOutbound = outboundPayments.reduce((sum, p) => sum + p.amount, 0);
  const netCashFlow = totalInbound - totalOutbound;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Payments</h1>
          <p className="text-gray-500">Track inbound and outbound payments</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowCustomerModal(true)}
            className="px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 flex items-center"
          >
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
            </svg>
            Pay from Customer
          </button>
          <button
            onClick={() => setShowVendorModal(true)}
            className="px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 flex items-center"
          >
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
            Pay to Vendor
          </button>
          <button
            onClick={() => {
              setEditingPayment(null);
              setShowModal(true);
            }}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 flex items-center"
          >
            <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
            </svg>
            Record Payment
          </button>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
          <p className="text-sm text-gray-500">Total Inbound</p>
          <p className="text-xl font-bold text-green-600">{formatCurrency(totalInbound)}</p>
          <p className="text-xs text-gray-400 mt-1">{inboundPayments.length} payments</p>
        </div>
        <div className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
          <p className="text-sm text-gray-500">Total Outbound</p>
          <p className="text-xl font-bold text-red-600">{formatCurrency(totalOutbound)}</p>
          <p className="text-xs text-gray-400 mt-1">{outboundPayments.length} payments</p>
        </div>
        <div className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
          <p className="text-sm text-gray-500">Net Cash Flow</p>
          <p className={`text-xl font-bold ${netCashFlow >= 0 ? 'text-blue-600' : 'text-red-600'}`}>
            {formatCurrency(netCashFlow)}
          </p>
        </div>
      </div>

      {/* Search + Filter */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
        <div className="relative flex-1 max-w-sm">
          <svg className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
          </svg>
          <input
            type="text"
            placeholder="Search payments…"
            value={searchTerm}
            onChange={e => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
          {searchTerm && (
            <button onClick={() => setSearchTerm('')} className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12"/></svg>
            </button>
          )}
        </div>
      <div className="flex items-center space-x-2">
        {['all', 'inbound', 'outbound'].map((type) => (
          <button
            key={type}
            onClick={() => setFilterType(type)}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
              filterType === type
                ? 'bg-blue-600 text-white'
                : 'bg-white text-gray-600 hover:bg-gray-100'
            }`}
          >
            {type.charAt(0).toUpperCase() + type.slice(1)}
          </button>
        ))}
      </div>
      </div>

      {/* Payments Table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table className="w-full">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
              <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 uppercase">Reference</th>
              <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 uppercase">Description / Invoice</th>
              <th className="px-6 py-4 text-left text-xs font-medium text-gray-500 uppercase">Account</th>
              <th className="px-6 py-4 text-center text-xs font-medium text-gray-500 uppercase">Type</th>
              <th className="px-6 py-4 text-center text-xs font-medium text-gray-500 uppercase">Method</th>
              <th className="px-6 py-4 text-right text-xs font-medium text-gray-500 uppercase">Amount</th>
              <th className="px-6 py-4 text-center text-xs font-medium text-gray-500 uppercase">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {paymentPagination.paginated.map((payment) => {
              const linkedInvoice = payment.invoiceId ? invoices.find(i => i.id === payment.invoiceId) : null;
              return (
                <tr key={payment.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 text-sm text-gray-900">{formatDate(payment.date)}</td>
                  <td className="px-6 py-4 text-sm font-mono text-gray-900">
                    <div>{payment.number || payment.reference}</div>
                    {payment.reference && payment.reference !== payment.number && <div className="text-xs text-gray-400">{payment.reference}</div>}
                  </td>
                  <td className="px-6 py-4">
                    <div>
                      {linkedInvoice ? (
                        <span className="text-sm text-blue-600">Invoice {linkedInvoice.number}</span>
                      ) : payment.purchaseCostNumber ? (
                        <span className="text-sm text-orange-600">PO {payment.purchaseCostNumber}</span>
                      ) : (
                        <span className="text-sm text-gray-900">{payment.description}</span>
                      )}
                      {payment.companyName && (
                        <p className="text-xs text-gray-500 mt-0.5 flex items-center gap-1">
                          <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16" /></svg>
                          {payment.companyName}
                          {payment.isContactPayment && <span className="text-green-600 font-medium">(contact pay)</span>}
                        </p>
                      )}
                      {payment.notes && !payment.companyName && (
                        <p className="text-xs text-gray-500 mt-0.5">{payment.notes}</p>
                      )}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-700">
                    {(() => {
                      const acc = payment.accountId ? accounts.find(a => a.id === payment.accountId) : null;
                      return acc
                        ? <span className="font-mono text-xs bg-gray-100 px-2 py-0.5 rounded">{acc.code} · {acc.name}</span>
                        : <span className="text-gray-400 text-xs">—</span>;
                    })()}
                  </td>
                  <td className="px-6 py-4 text-center">
                    <span className={`inline-flex px-3 py-1 text-xs font-medium rounded-full ${
                      (payment.type === 'inbound' || payment.invoiceId)
                        ? 'bg-green-100 text-green-700'
                        : 'bg-red-100 text-red-700'
                    }`}>
                      {(payment.type === 'inbound' || payment.invoiceId) ? 'Inbound' : 'Outbound'}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-center">
                    <span className={`inline-flex px-3 py-1 text-xs font-medium rounded-full ${getMethodColor(payment.method)}`}>
                      {getMethodLabel(payment.method)}
                    </span>
                  </td>
                  <td className={`px-6 py-4 text-right text-sm font-medium ${
                    (payment.type === 'inbound' || payment.invoiceId) ? 'text-green-600' : 'text-red-600'
                  }`}>
                    {(payment.type === 'inbound' || payment.invoiceId) ? '+' : '-'}{formatCurrency(payment.amount)}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center justify-center space-x-2">
                      <button
                        onClick={() => printPaymentVoucher(payment)}
                        className="p-2 text-purple-600 hover:bg-purple-50 rounded-lg transition-colors"
                        title="Print Voucher"
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                        </svg>
                      </button>
                      <button
                        onClick={() => handleEdit(payment)}
                        className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition-colors"
                        title="Edit"
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                        </svg>
                      </button>
                      <button
                        onClick={() => handleDelete(payment.id)}
                        className="p-2 text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                        title="Delete"
                      >
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                        </svg>
                      </button>
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        <Pagination
          page={paymentPagination.page}
          pageCount={paymentPagination.pageCount}
          onPageChange={paymentPagination.setPage}
          total={paymentPagination.total}
          pageSize={paymentPagination.pageSize}
        />
      </div>

      {/* Modal */}
      {showModal && (
        <PaymentModal
          payment={editingPayment}
          invoices={invoices}
          accounts={accounts}
          companies={companies}
          purchaseCosts={purchaseCosts}
          onSave={handleSave}
          onClose={() => {
            setShowModal(false);
            setEditingPayment(null);
          }}
        />
      )}
      {showCustomerModal && (
        <CustomerPaymentModal
          companies={companies}
          accounts={accounts}
          onSave={(result) => {
            loadData();
            setShowCustomerModal(false);
          }}
          onClose={() => setShowCustomerModal(false)}
        />
      )}
      {showVendorModal && (
        <VendorPaymentModal
          companies={companies}
          purchaseCosts={purchaseCosts}
          accounts={accounts}
          onSave={(result) => {
            loadData();
            setShowVendorModal(false);
          }}
          onClose={() => setShowVendorModal(false)}
        />
      )}
    </div>
  );
}

function PaymentModal({ payment, invoices, accounts, companies = [], purchaseCosts = [], onSave, onClose }) {
  const user = getCurrentUser();
  const unpaidInvoices = invoices.filter(
    i => ['confirmed', 'sent', 'partial'].includes(i.status) &&
         (Number(i.balanceDue ?? i.total) || 0) > 0
  );

  // Smart account type suggestions
  const cashAccounts     = accounts.filter(a => a.type === 'asset');
  const arAccounts       = accounts.filter(a => a.type === 'asset');
  const expenseAccounts  = accounts.filter(a => a.type === 'expense');
  const apAccounts       = accounts.filter(a => a.type === 'liability');

  const defaultCashId    = accounts.find(a => a.code === '1000')?.id || accounts[0]?.id || '';
  const defaultArId      = accounts.find(a => a.code === '1200')?.id || '';
  const defaultExpId     = accounts.find(a => a.code === '5000')?.id || '';
  const defaultApId      = accounts.find(a => a.code === '2000')?.id || '';

  const [formData, setFormData] = useState(payment || {
    date: new Date().toISOString().split('T')[0],
    type: 'inbound',
    amount: 0,
    method: 'bank_transfer',
    reference: '',
    invoiceId: null,
    invoiceNumber: '',
    accountId: defaultCashId,           // cash/bank (debit for inbound, credit for outbound)
    arAccountId: defaultArId,           // AR account (credit for inbound)
    expenseAccountId: defaultExpId,     // Expense account (debit for outbound)
    description: '',
    notes: '',
    recordedBy: user?.role
  });

  const handleTypeChange = (type) => {
    setFormData({
      ...formData,
      type,
      invoiceId: type === 'inbound' ? formData.invoiceId : null,
      invoiceNumber: type === 'inbound' ? formData.invoiceNumber : ''
    });
  };

  const handleInvoiceChange = (invoiceId) => {
    const invoice = invoices.find(i => i.id === invoiceId);
    if (invoice) {
      // Default to the outstanding balance, not the original total —
      // otherwise a partial payment overpays the invoice.
      const due = Number(invoice.balanceDue ?? invoice.total) || 0;
      setFormData({
        ...formData,
        invoiceId,
        invoiceNumber: invoice.number,
        // Carry the customer companyId & name so AR ledger links correctly
        companyId: invoice.companyId || formData.companyId,
        companyName: invoice.companyName || formData.companyName,
        amount: due
      });
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (formData.type === 'outbound' && !formData.description) {
      alert('Please provide a description for outbound payments');
      return;
    }
    // Ensure isVendorPayment is set correctly so the store uses AP/Cash journal entry
    const isVendorPay = formData.type === 'outbound' && !!formData.purchaseCostId;
    onSave({ ...formData, isVendorPayment: isVendorPay || !!formData.isVendorPayment });
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-xl p-6 w-full max-w-md">
        <h2 className="text-xl font-bold text-gray-900 mb-4">
          {payment ? 'Edit Payment' : 'Record Payment'}
        </h2>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Payment Date</label>
            <input
              type="date"
              value={formData.date}
              onChange={(e) => setFormData({ ...formData, date: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Payment Type</label>
            <div className="flex space-x-4">
              <label className="flex items-center">
                <input
                  type="radio"
                  value="inbound"
                  checked={formData.type === 'inbound'}
                  onChange={() => handleTypeChange('inbound')}
                  className="mr-2"
                />
                <span className="text-sm">Inbound (Receive)</span>
              </label>
              <label className="flex items-center">
                <input
                  type="radio"
                  value="outbound"
                  checked={formData.type === 'outbound'}
                  onChange={() => handleTypeChange('outbound')}
                  className="mr-2"
                />
                <span className="text-sm">Outbound (Pay)</span>
              </label>
            </div>
          </div>

          {formData.type === 'inbound' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Link to Invoice (Optional)</label>
              <select
                value={formData.invoiceId || ''}
                onChange={(e) => handleInvoiceChange(e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="">No invoice (standalone payment)</option>
                {unpaidInvoices.map((inv) => (
                  <option key={inv.id} value={inv.id}>
                    {inv.number} - {inv.companyName || inv.customerName || ''} — Balance: ${(inv.balanceDue ?? inv.total ?? 0).toLocaleString()}
                  </option>
                ))}
              </select>
            </div>
          )}

          {formData.type === 'outbound' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
              <input
                type="text"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                placeholder="e.g., Vendor payment - Supply Co"
                required
              />
            </div>
          )}

          {formData.type === 'outbound' && (() => {
            const vendorCos = companies.filter(c => c.type === 'vendor' || c.isVendor);
            const vendorPCs = formData.vendorId
              ? purchaseCosts.filter(pc => pc.vendorId === formData.vendorId && pc.status !== 'paid')
              : [];
            return (
              <>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Vendor (Optional)</label>
                  <select
                    value={formData.vendorId || ''}
                    onChange={(e) => {
                      const vendor = companies.find(c => c.id === e.target.value);
                      setFormData({ ...formData, vendorId: e.target.value, companyId: e.target.value, companyName: vendor?.name || '', purchaseCostId: null, purchaseCostNumber: '' });
                    }}
                    className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                  >
                    <option value="">— No vendor —</option>
                    {vendorCos.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}
                  </select>
                </div>
                {vendorPCs.length > 0 && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Link to Purchase Cost (Optional)</label>
                    <select
                      value={formData.purchaseCostId || ''}
                      onChange={(e) => {
                        const pc = vendorPCs.find(p => p.id === e.target.value);
                        setFormData({ ...formData, purchaseCostId: e.target.value || null, purchaseCostNumber: pc?.number || '', amount: pc ? Number(pc.balanceDue ?? pc.amount) || 0 : formData.amount });
                      }}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="">— No purchase cost —</option>
                      {vendorPCs.map(pc => <option key={pc.id} value={pc.id}>{pc.number} — ${(pc.balanceDue ?? pc.amount ?? 0).toLocaleString()} due</option>)}
                    </select>
                  </div>
                )}
              </>
            );
          })()}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              {formData.type === 'inbound' ? 'Deposit Account (Cash/Bank)' : 'Payment Account (Cash/Bank)'}
              <span className="ml-1 text-xs text-gray-400">credited on outbound, debited on inbound</span>
            </label>
            <select
              value={formData.accountId || ''}
              onChange={(e) => setFormData({ ...formData, accountId: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="">— None —</option>
              {cashAccounts.map(a => (
                <option key={a.id} value={a.id}>{a.code} · {a.name}</option>
              ))}
            </select>
          </div>

          {formData.type === 'inbound' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Accounts Receivable Account
                <span className="ml-1 text-xs text-gray-400">credited on receipt</span>
              </label>
              <select
                value={formData.arAccountId || ''}
                onChange={(e) => setFormData({ ...formData, arAccountId: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="">— Use default (1200) —</option>
                {arAccounts.map(a => (
                  <option key={a.id} value={a.id}>{a.code} · {a.name}</option>
                ))}
              </select>
            </div>
          )}

          {formData.type === 'outbound' && (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Expense / Cost Account
                <span className="ml-1 text-xs text-gray-400">debited on payment</span>
              </label>
              <select
                value={formData.expenseAccountId || ''}
                onChange={(e) => setFormData({ ...formData, expenseAccountId: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="">— Use default (5000) —</option>
                {expenseAccounts.map(a => (
                  <option key={a.id} value={a.id}>{a.code} · {a.name}</option>
                ))}
              </select>
            </div>
          )}

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Amount</label>
            <input
              type="number"
              value={formData.amount}
              onChange={(e) => setFormData({ ...formData, amount: parseFloat(e.target.value) || 0 })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              step="0.01"
              min="0"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Payment Method</label>
            <select
              value={formData.method}
              onChange={(e) => setFormData({ ...formData, method: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            >
              <option value="cash">Cash</option>
              <option value="check">Check</option>
              <option value="bank_transfer">Bank Transfer</option>
              <option value="credit_card">Credit Card</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Reference / Check #</label>
            <input
              type="text"
              value={formData.reference}
              onChange={(e) => setFormData({ ...formData, reference: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              placeholder="e.g., CHK-1234 or TRF-5678"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Notes (Optional)</label>
            <textarea
              value={formData.notes}
              onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
              rows="2"
            />
          </div>

          <div className="flex space-x-3 pt-4">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
            >
              Save Payment
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
// ─── Customer Payment Modal ────────────────────────────────────────────────────
// Allows accounting to receive a payment from a customer and auto-distribute
// it across outstanding invoices (oldest-first / FIFO), deducting the amount
// owed by that customer accordingly.
function CustomerPaymentModal({ companies, accounts = [], onSave, onClose }) {
  const [companyId, setCompanyId]   = useState('');
  const [amount,    setAmount]      = useState('');
  const [method,    setMethod]      = useState('bank_transfer');
  const [reference, setReference]   = useState('');
  const [accountId, setAccountId]   = useState(accounts.find(a => a.code === '1000')?.id || accounts[0]?.id || '');
  const [arAccountId, setArAccountId] = useState(accounts.find(a => a.code === '1200')?.id || '');
  const [date,      setDate]        = useState(new Date().toISOString().split('T')[0]);
  const [notes,     setNotes]       = useState('');
  const [result,    setResult]      = useState(null); // breakdown after save
  const [useWalletOnly, setUseWalletOnly] = useState(false); // apply wallet to invoices without new payment

  // Live ledger for the selected customer
  const ledger = companyId ? getCustomerLedger(companyId) : null;
  const walletBalance = companyId ? getCustomerWalletBalance(companyId) : 0;
  const selectedCompany = companies.find(c => c.id === companyId);
  const parsedAmount = parseFloat(amount) || 0;

  // Wallet coverage calculations
  const walletCovers  = ledger ? Math.min(walletBalance, ledger.balanceDue) : 0;
  const walletApplied = parsedAmount > 0 ? Math.min(walletBalance, parsedAmount) : walletCovers;
  const netCashNeeded = ledger ? Math.max(ledger.balanceDue - walletCovers, 0) : 0;

  const formatCurrency = (v) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(v) || 0);

  const handleCompanyChange = (id) => {
    setCompanyId(id);
    setAmount('');
    setResult(null);
    setUseWalletOnly(false);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!companyId) return alert('Please select a customer.');

    // Wallet-only mode: apply wallet credit to outstanding invoices
    if (useWalletOnly) {
      const wb = getCustomerWalletBalance(companyId);
      if (wb <= 0.001) return alert('No wallet balance to apply.');
      const { unpaid } = getCustomerLedger(companyId);
      if (unpaid.length === 0) return alert('No outstanding invoices to apply wallet credit to.');
      const created = applyContactPayment({
        companyId,
        companyName: selectedCompany?.name || '',
        amount: 0, // no new cash — wallet auto-applies inside applyContactPayment
        method: 'wallet',
        date,
        notes: notes || `Wallet credit applied for ${selectedCompany?.name}`,
        accountId: accountId || null,
        arAccountId: arAccountId || null,
      });
      setResult(created);
      onSave(created);
      return;
    }

    if (parsedAmount <= 0) return alert('Please enter a valid amount.');

    const created = applyContactPayment({
      companyId,
      companyName: selectedCompany?.name || '',
      amount: parsedAmount,
      method,
      date,
      notes: notes || `Payment from ${selectedCompany?.name}`,
      accountId: accountId || null,
      arAccountId: arAccountId || null,
    });

    setResult(created);
    onSave(created);
  };

  const customerCompanies = companies.filter(c => c.type !== 'vendor');

  return (
    <div className="fixed inset-0 bg-black bg-opacity-60 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg max-h-[92vh] overflow-y-auto">
        <div className="p-6">
          {/* Header */}
          <div className="flex items-start justify-between mb-5">
            <div>
              <h2 className="text-lg font-bold text-gray-900">Pay from Customer</h2>
              <p className="text-xs text-gray-500 mt-0.5">Receive a payment and deduct from what the customer owes</p>
            </div>
            <button onClick={onClose} className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Success breakdown */}
          {result && (
            <div className="mb-5 bg-emerald-50 border border-emerald-200 rounded-xl p-4">
              <div className="flex items-center gap-2 mb-3">
                <svg className="w-5 h-5 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span className="text-sm font-semibold text-emerald-800">Payment recorded — {result.length} transaction{result.length !== 1 ? 's' : ''} created</span>
              </div>
              <div className="space-y-1.5">
                {result.map((p, i) => (
                  <div key={p.id || i} className="flex justify-between text-sm">
                    <span className="text-emerald-700">
                      {p.fromWallet
                        ? `💳 Wallet → Invoice ${p.invoiceNumber}`
                        : p.addedToWallet
                          ? `🪙 Added to wallet`
                          : p.invoiceNumber ? `Invoice ${p.invoiceNumber}` : 'Advance / Overpayment'}
                    </span>
                    <span className="font-bold text-emerald-800">{formatCurrency(p.addedToWallet ? p.walletAmount : p.amount)}</span>
                  </div>
                ))}
              </div>
              {result.some(p => p.addedToWallet) && (
                <p className="mt-3 text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
                  🪙 Overpayment added to customer's wallet. It will be automatically applied to future invoices.
                </p>
              )}
              <button onClick={onClose}
                className="mt-4 w-full px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 text-sm font-semibold">
                Done
              </button>
            </div>
          )}

          {!result && (
            <form onSubmit={handleSubmit} className="space-y-4">
              {/* Customer */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Customer *</label>
                <select
                  value={companyId} onChange={e => handleCompanyChange(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 text-sm"
                  required
                >
                  <option value="">— Select customer —</option>
                  {customerCompanies.map(c => (
                    <option key={c.id} value={c.id}>{c.name}</option>
                  ))}
                </select>
              </div>

              {/* Ledger summary */}
              {ledger && companyId && (
                <div className="bg-gray-50 border border-gray-200 rounded-xl p-4">
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Customer Balance</p>
                  <div className="grid grid-cols-3 gap-3 text-center">
                    <div>
                      <p className="text-xs text-gray-400">Invoiced</p>
                      <p className="text-sm font-bold text-gray-800">{formatCurrency(ledger.totalInvoiced)}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400">Paid</p>
                      <p className="text-sm font-bold text-green-700">{formatCurrency(ledger.totalPaid)}</p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400">Balance Due</p>
                      <p className={`text-sm font-bold ${ledger.balanceDue > 0 ? 'text-red-600' : 'text-green-600'}`}>
                        {formatCurrency(ledger.balanceDue)}
                      </p>
                    </div>
                  </div>

                  {/* Wallet balance */}
                  {walletBalance > 0.001 && (
                    <div className="mt-3 border-t border-amber-200 pt-3 bg-amber-50 -mx-4 -mb-4 px-4 pb-4 rounded-b-xl">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <span className="text-base">🪙</span>
                          <div>
                            <p className="text-xs font-semibold text-amber-700">Wallet Credit</p>
                            <p className="text-sm font-bold text-amber-800">{formatCurrency(walletBalance)}</p>
                          </div>
                        </div>
                        {ledger.unpaid.length > 0 && (
                          <button
                            type="button"
                            onClick={() => setUseWalletOnly(w => !w)}
                            className={`px-3 py-1.5 text-xs font-semibold rounded-lg border transition-colors ${
                              useWalletOnly
                                ? 'bg-amber-500 text-white border-amber-500'
                                : 'bg-white text-amber-700 border-amber-400 hover:bg-amber-100'
                            }`}
                          >
                            {useWalletOnly ? '✓ Apply wallet' : 'Apply wallet to invoices'}
                          </button>
                        )}
                      </div>
                      {useWalletOnly && (
                        <p className="mt-2 text-xs text-amber-700">
                          Will apply up to {formatCurrency(walletBalance)} from wallet to {ledger.unpaid.length} outstanding invoice{ledger.unpaid.length !== 1 ? 's' : ''} (oldest first). No new cash needed.
                        </p>
                      )}
                    </div>
                  )}

                  {ledger.unpaid.length > 0 && !walletBalance && (
                    <div className="mt-3 border-t border-gray-200 pt-3">
                      <p className="text-xs font-semibold text-gray-500 mb-1.5">Outstanding Invoices (payment applied oldest-first)</p>
                      <div className="space-y-1">
                        {ledger.unpaid.slice(0, 5).map(inv => (
                          <div key={inv.id} className="flex justify-between text-xs text-gray-600">
                            <span className="font-mono">{inv.number}</span>
                            <span className="font-medium text-red-600">{formatCurrency(inv.balanceDue ?? inv.total)} due</span>
                          </div>
                        ))}
                        {ledger.unpaid.length > 5 && (
                          <p className="text-xs text-gray-400">+{ledger.unpaid.length - 5} more invoices</p>
                        )}
                      </div>
                    </div>
                  )}
                  {ledger.unpaid.length === 0 && (
                    <p className="mt-2 text-xs text-emerald-600 font-medium">✓ No outstanding invoices — any amount will be added to wallet</p>
                  )}
                  {/* Net cash hint when wallet covers part */}
                  {walletCovers > 0.001 && ledger.unpaid.length > 0 && !useWalletOnly && (
                    <div className="mt-3 border-t border-amber-200 pt-2 text-xs text-amber-700">
                      💡 Wallet covers <strong>{formatCurrency(walletCovers)}</strong> — you only need <strong>{formatCurrency(netCashNeeded)}</strong> in cash
                    </div>
                  )}
                </div>
              )}

              {/* Amount — hidden when using wallet-only mode */}
              {!useWalletOnly && (
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Amount Received *</label>
                <input
                  type="number" min="0.01" step="0.01" value={amount}
                  onChange={e => setAmount(e.target.value)}
                  placeholder="0.00"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 text-sm font-semibold"
                  required={!useWalletOnly}
                />
                {ledger && parsedAmount > 0 && (
                  <div className="flex gap-2 mt-2">
                    <button type="button"
                      onClick={() => setAmount(netCashNeeded > 0.001 ? netCashNeeded.toFixed(2) : ledger.balanceDue.toFixed(2))}
                      className="px-2 py-1 text-xs bg-emerald-100 text-emerald-700 rounded-lg hover:bg-emerald-200 font-medium">
                      {walletCovers > 0.001 ? `Cash needed (${formatCurrency(netCashNeeded)})` : `Full balance (${formatCurrency(ledger.balanceDue)})`}
                    </button>
                  </div>
                )}
                {ledger && parsedAmount > 0 && (
                  <div className="mt-1.5 space-y-0.5">
                    {walletBalance > 0.001 && walletApplied > 0.001 && (
                      <p className="text-xs font-medium text-amber-600">
                        🪙 {formatCurrency(walletApplied)} will be taken from wallet automatically
                      </p>
                    )}
                    <p className={`text-xs font-medium ${parsedAmount + walletApplied >= ledger.balanceDue - 0.001 ? 'text-emerald-600' : 'text-blue-600'}`}>
                      {parsedAmount + walletApplied >= ledger.balanceDue - 0.001
                        ? `✓ Settles all outstanding invoices${parsedAmount + walletApplied > ledger.balanceDue + 0.001 ? ` + ${formatCurrency(parsedAmount + walletApplied - ledger.balanceDue)} → wallet` : ''}`
                        : `Remaining balance after: ${formatCurrency(ledger.balanceDue - parsedAmount - walletApplied)}`}
                    </p>
                  </div>
                )}
              </div>
              )}

              {/* Date */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Payment Date *</label>
                <input
                  type="date" value={date} onChange={e => setDate(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 text-sm"
                  required
                />
              </div>

              {/* Method */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Payment Method *</label>
                <select value={method} onChange={e => setMethod(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 text-sm">
                  <option value="cash">Cash</option>
                  <option value="check">Check</option>
                  <option value="bank_transfer">Bank Transfer</option>
                  <option value="credit_card">Credit Card</option>
                </select>
              </div>

              {/* Reference */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Reference / Check #</label>
                <input type="text" value={reference} onChange={e => setReference(e.target.value)}
                  placeholder="e.g. TRF-001"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 text-sm"
                />
              </div>

              {/* Deposit Account */}
              {accounts.length > 0 && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Deposit Account (Cash/Bank) <span className="text-xs text-gray-400">debited</span></label>
                  <select value={accountId} onChange={e => setAccountId(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 text-sm">
                    <option value="">— None —</option>
                    {accounts.filter(a => a.type === 'asset').map(a => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}
                  </select>
                </div>
              )}

              {/* AR Account */}
              {accounts.length > 0 && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Accounts Receivable Account <span className="text-xs text-gray-400">credited</span></label>
                  <select value={arAccountId} onChange={e => setArAccountId(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 text-sm">
                    <option value="">— Use default (1200) —</option>
                    {accounts.filter(a => a.type === 'asset').map(a => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}
                  </select>
                </div>
              )}

              {/* Notes */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                <textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2}
                  placeholder="Optional note"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 text-sm resize-none"
                />
              </div>

              <div className="flex gap-3 pt-1">
                <button type="button" onClick={onClose}
                  className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 text-sm font-medium">
                  Cancel
                </button>
                <button type="submit"
                  className="flex-1 px-4 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 text-sm font-semibold">
                  Apply Payment
                </button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Vendor Payment Modal ──────────────────────────────────────────────────────
// Send an outbound payment to a vendor and auto-distribute across unpaid
// purchase costs (oldest-first / FIFO), reducing amounts owed.
function VendorPaymentModal({ companies, purchaseCosts = [], accounts = [], onSave, onClose }) {
  const [companyId, setCompanyId] = useState('');
  const [amount, setAmount]       = useState('');
  const [method, setMethod]       = useState('bank_transfer');
  const [reference, setReference] = useState('');
  const [accountId, setAccountId] = useState(accounts.find(a => a.code === '1000')?.id || accounts[0]?.id || '');
  const [expenseAccountId, setExpenseAccountId] = useState(accounts.find(a => a.code === '5000')?.id || '');
  const [date, setDate]           = useState(new Date().toISOString().split('T')[0]);
  const [notes, setNotes]         = useState('');
  const [result, setResult]       = useState(null);

  const ledger = companyId ? getVendorLedger(companyId) : null;
  const selectedCompany = companies.find(c => c.id === companyId);
  const parsedAmount = parseFloat(amount) || 0;

  const formatCurrency = (v) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(v) || 0);

  const handleCompanyChange = (id) => { setCompanyId(id); setAmount(''); setResult(null); };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!companyId) return alert('Please select a vendor.');
    if (parsedAmount <= 0) return alert('Please enter a valid amount.');
    const created = applyVendorPayment({
      companyId,
      companyName: selectedCompany?.name || '',
      amount: parsedAmount,
      method,
      date,
      notes: notes || `Payment to ${selectedCompany?.name}`,
      accountId: accountId || null,
      expenseAccountId: expenseAccountId || null,
    });
    setResult(created);
    onSave(created);
  };

  // Unpaid purchase costs for the selected vendor
  const vendorCosts = companyId
    ? purchaseCosts
        .filter(c => c.vendorId === companyId && c.status !== 'paid' && (Number(c.balanceDue ?? c.amount) || 0) > 0)
        .sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt))
    : [];

  const vendorCompanies = companies.filter(c => c.type === 'vendor' || c.isVendor);

  return (
    <div className="fixed inset-0 bg-black bg-opacity-60 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg max-h-[92vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex items-start justify-between mb-5">
            <div>
              <h2 className="text-lg font-bold text-gray-900">Pay to Vendor</h2>
              <p className="text-xs text-gray-500 mt-0.5">Send an outbound payment and apply it to outstanding purchase costs</p>
            </div>
            <button onClick={onClose} className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {result && (
            <div className="mb-5 bg-orange-50 border border-orange-200 rounded-xl p-4">
              <div className="flex items-center gap-2 mb-3">
                <svg className="w-5 h-5 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span className="text-sm font-semibold text-orange-800">Payment sent — {result.length} transaction{result.length !== 1 ? 's' : ''} created</span>
              </div>
              <div className="space-y-1.5">
                {result.map((p, i) => (
                  <div key={p.id || i} className="flex justify-between text-sm">
                    <span className="text-orange-700">{p.purchaseCostNumber ? `PO ${p.purchaseCostNumber}` : 'Advance / Overpayment'}</span>
                    <span className="font-bold text-orange-800">{formatCurrency(p.amount)}</span>
                  </div>
                ))}
              </div>
              <button onClick={onClose} className="mt-4 w-full px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 text-sm font-semibold">Done</button>
            </div>
          )}

          {!result && (
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Vendor *</label>
                <select value={companyId} onChange={e => handleCompanyChange(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 text-sm" required>
                  <option value="">— Select vendor —</option>
                  {vendorCompanies.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}
                </select>
              </div>

              {ledger && companyId && (
                <div className="bg-gray-50 border border-gray-200 rounded-xl p-4">
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Vendor Balance</p>
                  <div className="grid grid-cols-3 gap-3 text-center">
                    <div><p className="text-xs text-gray-400">Total Costs</p><p className="text-sm font-bold text-gray-800">{formatCurrency(ledger.totalCosts)}</p></div>
                    <div><p className="text-xs text-gray-400">Paid</p><p className="text-sm font-bold text-green-700">{formatCurrency(ledger.totalPaid)}</p></div>
                    <div><p className="text-xs text-gray-400">Balance Due</p><p className={`text-sm font-bold ${ledger.balanceDue > 0 ? 'text-red-600' : 'text-green-600'}`}>{formatCurrency(ledger.balanceDue)}</p></div>
                  </div>
                  {vendorCosts.length > 0 && (
                    <div className="mt-3 border-t border-gray-200 pt-3">
                      <p className="text-xs font-semibold text-gray-500 mb-1.5">Outstanding Purchase Costs (oldest-first)</p>
                      <div className="space-y-1">
                        {vendorCosts.slice(0, 5).map(c => (
                          <div key={c.id} className="flex justify-between text-xs text-gray-600">
                            <span className="font-mono">{c.number || c.id}</span>
                            <span className="font-medium text-red-600">{formatCurrency(c.balanceDue ?? c.amount)} due</span>
                          </div>
                        ))}
                        {vendorCosts.length > 5 && <p className="text-xs text-gray-400">+{vendorCosts.length - 5} more</p>}
                      </div>
                    </div>
                  )}
                  {vendorCosts.length === 0 && (
                    <p className="mt-2 text-xs text-emerald-600 font-medium">✓ No outstanding purchase costs — any amount will be recorded as advance</p>
                  )}
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Amount to Pay *</label>
                <input type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)}
                  placeholder="0.00"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 text-sm font-semibold" required />
                {ledger && parsedAmount > 0 && (
                  <div className="flex gap-2 mt-2">
                    <button type="button" onClick={() => setAmount(ledger.balanceDue.toFixed(2))}
                      className="px-2 py-1 text-xs bg-orange-100 text-orange-700 rounded-lg hover:bg-orange-200 font-medium">
                      Full balance ({formatCurrency(ledger.balanceDue)})
                    </button>
                  </div>
                )}
                {ledger && parsedAmount > 0 && (
                  <p className={`mt-1.5 text-xs font-medium ${parsedAmount >= ledger.balanceDue - 0.001 ? 'text-emerald-600' : 'text-blue-600'}`}>
                    {parsedAmount >= ledger.balanceDue - 0.001
                      ? `✓ Settles all outstanding costs${parsedAmount > ledger.balanceDue + 0.001 ? ` + ${formatCurrency(parsedAmount - ledger.balanceDue)} advance` : ''}`
                      : `Remaining balance after: ${formatCurrency(ledger.balanceDue - parsedAmount)}`}
                  </p>
                )}
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Payment Date *</label>
                <input type="date" value={date} onChange={e => setDate(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 text-sm" required />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Payment Method *</label>
                <select value={method} onChange={e => setMethod(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 text-sm">
                  <option value="cash">Cash</option>
                  <option value="check">Check</option>
                  <option value="bank_transfer">Bank Transfer</option>
                  <option value="credit_card">Credit Card</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Reference / Check #</label>
                <input type="text" value={reference} onChange={e => setReference(e.target.value)}
                  placeholder="e.g. TRF-001"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 text-sm" />
              </div>

              {accounts.length > 0 && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Payment Account (Cash/Bank) <span className="text-xs text-gray-400">credited</span></label>
                  <select value={accountId} onChange={e => setAccountId(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 text-sm">
                    <option value="">— None —</option>
                    {accounts.filter(a => a.type === 'asset').map(a => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}
                  </select>
                </div>
              )}

              {accounts.length > 0 && (
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Expense / Cost Account <span className="text-xs text-gray-400">debited</span></label>
                  <select value={expenseAccountId} onChange={e => setExpenseAccountId(e.target.value)}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 text-sm">
                    <option value="">— Use default (5000) —</option>
                    {accounts.filter(a => a.type === 'expense' || a.type === 'liability').map(a => <option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}
                  </select>
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                <textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2}
                  placeholder="Optional note"
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 text-sm resize-none" />
              </div>

              <div className="flex gap-3 pt-1">
                <button type="button" onClick={onClose}
                  className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 text-sm font-medium">Cancel</button>
                <button type="submit"
                  className="flex-1 px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 text-sm font-semibold">Send Payment</button>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}
